nameOverride: ""
fullnameOverride: ""

imageRepository: louisleblin/prometheus-switchbot-exporter
imagePullPolicy: Always

metricsPort: 8080

securityContext:
  # TODO: only import the bluetooth device
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
