apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-switchbot-exporter.fullname" . }}
  labels:
    {{- include "prometheus-switchbot-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "prometheus-switchbot-exporter.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
