{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-switchbot-exporter.fullname" . }}
  labels:
    {{- include "prometheus-switchbot-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-switchbot-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    {{- with .Values.serviceMonitorOptions }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{ end }}