name: Release

on:
  push:
    branches:
      - master

jobs:
  github-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  publish-docker:
    name: Publish Docker image
    needs: github-release
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: louisleblin/prometheus-switchbot-exporter:${{ needs.github-release.outputs.tag }}

  publish-helm:
    name: Publish Helm chart
    needs: github-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master
          ref: master
      
      - name: Create Helm chart
        run: helm package master/charts/prometheus-switchbot-exporter --app-version ${{ needs.github-release.outputs.tag }} --version ${{ needs.github-release.outputs.tag }}

      - name: Checkout GitHub pages branch
        uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages

      - name: Push Helm chart
        run: |
          mv *.tgz gh-pages/
          cd gh-pages/
          helm repo index --url https://charts.blin.dev/ --merge index.yaml .

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "Publish chart prometheus-switchbot-exporter=$tag"
          git push
