name: Release

on:
  push:
    branches:
      - master

jobs:
  github-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  publish-docker:
    name: Publish Docker image
    needs: github-release
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: louisleblin/prometheus-switchbot-exporter:${{ needs.github-release.outputs.tag }}

  publish-helm:
    name: Publish Helm chart
    needs: github-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Push chart to GitHub pages
        run: |
          tag=${{ needs.github-release.outputs.tag }}
          helm package charts/prometheus-switchbot-exporter --app-version $tag --version $tag

          git remote -v
          git worktree add .pages origin/gh-pages
          mv *.tgz .pages/
          cd .pages
          helm repo index --url https://charts.blin.dev/ --merge index.yaml .

          git add .
          git commit -am "Publish chart prometheus-switchbot-exporter=$tag"
          git push origin gh-pages